#!/bin/bash

sudo docker pull linuxserver/wireguard

sudo docker run -d \
  --name=wireguard \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  -e PUID=224 \
  -e PGID=321 \
  -e TZ=Pacific/Honolulu \
  -e PEERS=laptop,tablet,phone \
  -e PEERDNS=auto \
  -e SERVERURL=auto \
  -e SERVERPORT=51820 \
  -p 51820:51820/udp \
  -v ~/media/appdata/wireguard:/config \
  -v /lib/modules:/lib/modules \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --restart unless-stopped \
  linuxserver/wireguard
